### ISSUE TITLE
Make projectile dependency optional

### ISSUE THREAD

**Issue by articuluxe** [waymondo/frog-jump-buffer#1]
Only one method uses projectile, this dependency can be soft, allowing usage of this library even for those who do not use projectile.

**Comment by waymondo** [comment]
Hi there, sorry for the long delay. Is there any harm to having projectile installed if you aren't using it?

Currently I like that being able to filter buffers by the current project is a core feature of this package. There is a newer built-in package called `project.el` which is a bit under featured still, but if the implementation could be replicated with that, I would be encouraged to let `projectile` be a soft dependency / option for how this filtering could work.
