### ISSUE TITLE
Fixing keys

### ISSUE THREAD

**Issue by daphniz** [waymondo/frog-jump-buffer#15]
It might be a good idea to be able to fix keys to certain buffers.  Then, when working on a handful of buffers, one doesn't have to look each time to figure out which key to press.

**Comment by waymondo** [comment]
I don't think I'm going to add this specifically as requested to this package, for a few reasons:

* The package is intended to be used with dynamic and partial lists of buffers - sometimes buffers aren't present in the list.
* It also would potentially add a heavy setup for users end to take advantage of it.
* And once specifying keys for specific buffers is in place, I'd need to worry about collisions of multiple buffers having the same key, either by specific specification or from the default avy keys.

A couple ideas:

You could customize `frog-jump-buffer-sort` to always preference your buffers in a specific order, which would cause them to consistently have the same selection keys: https://github.com/waymondo/frog-jump-buffer/blob/master/frog-jump-buffer.el#L53

Perhaps a bookmarks package like [bm](https://github.com/joodland/bm) would be more useful if the intention is to have a key command that will reliably bring you to specific buffers.
