### ISSUE TITLE
frog-jump-buffer-other-window shows the content in the both buffer

### ISSUE THREAD

**Issue by yamatakau08** [waymondo/frog-jump-buffer#16]
I use the `frog-jump-buffer` following version on emacs 28.0.50 on Windows.
```
;; Package-Version: 20200114.1826
;; Package-Commit: 1eb289c9b2a4bbebb3065076750f54216ac9c718
;; Version: 0.1.4
```

When start emacs and shows "GNU Emacs" buffer means startup,
I execute `frog-jump-buffer-other-window` and select e.g. init.el.
After that, frog-jump-buffer splits the window.
But the both buffer shows init.el. (*)

I expect the one buffer shows the "GNU Emacs" and other shows "init.el"

(*) After that I execute the frog-jump-buffer-other-window and select e.g. frog-jump-buffer.el.
The same issue that both buffer shows frog-jump-buffer.el happen.

Is this issue happen on my environment only?

**Comment by waymondo** [comment]
Thanks for the detailed report. It does sound like this could be improved.

I'm guessing you are using `frog-jump-buffer-include-virtual-buffers` set to `t`?

**Comment by yamatakau08** [comment]
@waymondo 
Thank you for replying.

> I'm guessing you are using frog-jump-buffer-include-virtual-buffers set to t?

No. 
Without any configuration of frog-jump-buffer, I have this symptom.
I attached the video.
Could you check it.
![frog-jump-buffer-other-window](https://user-images.githubusercontent.com/13044987/91713633-19abde00-ebc5-11ea-873b-8ec30ffa5481.gif)

**Comment by yamatakau08** [comment]
My workaround is the following.
I'm not sure it's appropriate.
But it works fine for me.

```
  ;; redfine original function
  (defun frog-jump-buffer-find-or-create-buffer (res)
    "Switch to buffer, or if closed, find and create it first."
    (let ((buffer (if frog-jump-buffer-include-virtual-buffers
		      (find-file (assoc-default res (frog-jump-buffer-recentf-buffers)))
                    res)))
      (if frog-jump-buffer-target-other-window
          ;;(switch-to-buffer-other-window buffer) ; original
	  (progn
	    (message "[debug] frog-jump-buffer-find-or-create-buffer 1")
            (switch-to-buffer-other-window nil)) ; my modification
	(switch-to-buffer buffer))))
```

**Comment by waymondo** [comment]
Redefining the function to `(switch-to-buffer-other-window nil)` is not what you want, because it will always use the value of `other-buffer`, instead of the buffer you selected.

Your example is using `recentf`, which is what I meant by referencing `frog-jump-buffer-include-virtual-buffers` (which is not a variable you set, sorry for the confusion). I can recreate the symptom using the `recentf` filter, and it doesn't happen otherwise. Pushing a commit now that fixes.
