### ISSUE TITLE
Any idea why the colors are wrong?

### ISSUE THREAD

**Issue by bbigras** [waymondo/frog-jump-buffer#19]
Isn't it supposed to be a "dark theme" just like in your screenshot?

![image](https://user-images.githubusercontent.com/24027/92125766-e77dc480-edee-11ea-9f61-e206f7b51176.png)

```
  frog-jump-buffer               20200114.1826  external     The fastest buffer-jumping Emacs lisp package around.
  frog-menu                      0.2.11         external     Quickly pick items from ad hoc menus
```

**Comment by waymondo** [comment]
This package doesn't include any font faces or styling. There are faces defined in `posframe` and `frog-menu` that could be customized to match the theme of your choice. I'm using `apropropriate` myself, which supports these packages: https://github.com/waymondo/apropospriate-theme/blob/master/apropospriate.el#L261-L264

**Comment by bbigras** [comment]
Thanks.

**Comment by gsingh93** [comment]
I feel like this is really an issue with `frog-menu`. I've submitted a PR here: https://github.com/clemera/frog-menu/pull/15
