### ISSUE TITLE
1, 2,3,4,0 toggle doesn't work

### ISSUE THREAD

**Issue by adouzzy** [waymondo/frog-jump-buffer#2]
FYI, I am a evil user. I just cloned the frog-menu and buffer today.
The number toggle doesn't work for me. Pressing them makes emacs quit frog-menu.

**Comment by waymondo** [comment]
Does it work if you turn evil off? If not, what version of `avy` and `frog-menu` do you have installed?

**Comment by adouzzy** [comment]
I worked after I installed the melpa version.
