### ISSUE TITLE
Gracefully handle ESC (aka Quit signal)

### ISSUE THREAD

**Issue by whyfarer** [waymondo/frog-jump-buffer#21]
I just start using frog-jump-buffer and I'm quite enjoying it. Thanks!

Issue:

If I invoke frog-jump-buffer and then ESC out of it, I trigger the following error:

```Debugger entered--Lisp error: (error "Quit")
  signal(error ("Quit"))
  error("Quit")
  frog-jump-buffer()
  funcall-interactively(frog-jump-buffer)
  call-interactively(frog-jump-buffer nil nil)
  command-execute(frog-jump-buffer)``` 

It would be nice if hitting ESC didn't trigger the debugger and instead gracefully exitted the buffer menu (without any buffer change).

**Comment by waymondo** [comment]
Sorry for not looking at this for so long. I'm not opposed to adding support for `ESC` to be bound to dismiss the menu by default, as `C-g` does.

I'm not sure why pressing `ESC` would trigger the debugger for you however. Do you have `(toggle-debug-on-error)` enabled? Is there any other relevant config you can share?

**Comment by whyfarer** [comment]
Unfortunately, looks like I deleted frog-jump-buffer from my config since hitting this error all the time was too painful for me. I no longer have any idea how I had it setup. I don't think any other parts of my config would have contributed to unusual esc behavior though

**Comment by waymondo** [comment]
If you never set `debug-on-error`, which is not enabled in Emacs by default, the fallback of `(error "Quit")` will end up dismissing the menu like you were desiring.

Ideally this would be gracefully handled even if you are opting into the debugger behavior though.

**Comment by waymondo** [comment]
Just to follow up, I pushed a commit to bypass triggering the debugger when it is enabled on pressing `ESC`.
