### ISSUE TITLE
frog-jump-buffer-filter-same-project error outside project with project.el

### ISSUE THREAD

**Issue by vuori** [waymondo/frog-jump-buffer#26]
When using `frog-jump-buffer-filter-same-project` in a buffer outside a project with `frog-jump-buffer-project-package` set to `'project`, an error is raised due to nil from `(project-current)` being passed to `project-buffers`.

I guess this should have the same nil check that's in the projectile version of the code.

**Comment by waymondo** [comment]
Thanks for pointing this out, just pushed a commit for it
