### ISSUE TITLE
Option to customize `avy-background`

### ISSUE THREAD

**Issue by gsingh93** [waymondo/frog-jump-buffer#28]
This is how my posframe looks like at the moment:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/1012677/231857078-98102fe1-b2e6-4cf9-bcc2-ef8801871a04.png">

I'd like to set `avy-background` to `nil` so it looks like this:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1012677/231858023-c5c902f7-6ecb-471e-b847-456ea3adae6f.png">

But I don't want to set it globally, I only want it for frog jump. Would it makes sense to add a `frog-jump-buffer-avy-background` customizable variable to handle this?

**Comment by aatmunbaxi** [comment]
I think this can be solved by hooking a localized `avy-background` value to `frog-menu-after-init-hook`.
The following works for me
```
(defun my/frog-menu-hook () (
    (setq-local avy-background nil)
    )

(add-hook 'frog-menu-after-init-hook 'my/frog-menu-hook)
```

**Comment by waymondo** [comment]
sorry for the super long delay here. i think @aatmunbaxi's workaround works well enough as a quick fix.

if a first class solution was going to live in a package though, i would think it should be in `frog-menu`, since this is were other posframe-specific avy overrides live currently.
